### ISSUE TITLE
Assignment 1 Vis - Submission

### ISSUE THREAD

**Issue by a-lesser** [VIS-2129-F2020/alesser-vis#1]
Hi Carol,

I am submitting my first assignment for Vis. Here is the link to the html file:https://github.com/VIS-2129-F2020/alesser-vis/blob/master/Assignment-1-Vis-.html

Thank you,
Aron

**Comment by c-voulgaris** [comment]
This looks great! 

I don't have any comments on your code. I hope you had fun with this assignment.
