### ISSUE TITLE
Submitting Assignment #2 

### ISSUE THREAD

**Issue by a-lesser** [VIS-2129-F2020/alesser-vis#2]
Hi Carole,

Please find below the link to my second assignment. 

https://github.com/VIS-2129-F2020/alesser-vis/blob/master/Assignment-Vis-2---Mapping.html

Best,
Aron

**Comment by bauranov** [comment]
Good work! Here are some comments: 
- The link should be https://vis-2129-f2020.github.io/alesser-vis/filename, where *filename* is the name of your HTML file -https://vis-2129-f2020.github.io/alesser-vis/Assignment-Vis-2---Mapping. 
- At the beginning of a code chunk add {r, message=FALSE,warning=FALSE} to suppress messages and warnings in HTML. When you knit your file, go through the HTML and see if some code chunks are displaying the text you don't want (such as in the section Adding GDP, or cartogram). If there is such text, remove it with the code I mentioned above.
- I would encourage you to explore different colors and color palettes.
- Send me an email if something doesn't work, we'll fix it.
Keep up the good work!
