### ISSUE TITLE
Assignment 3 ready for grading

### ISSUE THREAD

**Issue by a-lesser** [VIS-2129-F2020/alesser-vis#3]
Hi Carole, Alex, and Taelor,

I am uploading my third assignment. The links are: 

https://vis-2129-f2020.github.io/alesser-vis/Vis-assignment-3.html

and

https://vis-2129-f2020.github.io/alesser-vis/Vis assignment 3.Rmd

Thank you,
Aron

**Comment by bauranov** [comment]
Interesting to see that the two richest neighborhoods in Boston don't have a single public school. Great work, very informative plots.
