### ISSUE TITLE
Assignment 4 Submission

### ISSUE THREAD

**Issue by a-lesser** [VIS-2129-F2020/alesser-vis#4]
Hi Carole, Alex, and Taelor,

Here are the links to my fourth assignment. 

https://vis-2129-f2020.github.io/alesser-vis/Vis Assignment 4_AL.Rmd

and 
https://vis-2129-f2020.github.io/alesser-vis/Vis-Assignment-4_AL.html

Thank you,
Aron

**Comment by bauranov** [comment]
Good work. Go through your html before submission and make sure all the headings are properly formatted and no messages or warnings are in the file.
